/* ==========================================
   ARCHIVO: 01_tablas.sql
   DESCRIPCIÓN: Creación de tablas con correcciones de edad y constraints.
   CAMBIOS REALIZADOS DEL DOC
   ========================================== */

-- 1. TABLAS DE UBICACIÓN
CREATE TABLE PAISES (
    id              NUMBER(3) NOT NULL,
    nombre          VARCHAR2(25) NOT NULL UNIQUE,
    continente      CHAR(2) NOT NULL,
    nacionalidad    VARCHAR2(15) NOT NULL,
    ue      CHAR(1) NOT NULL,
    CONSTRAINT PK_PAIS PRIMARY KEY (id),
    CONSTRAINT CK_CONTINENTE CHECK (continente IN ('AM','EU','OC','AS','AF')),
    CONSTRAINT CK_UE CHECK (ue IN ('S','N')) 
);


CREATE TABLE ESTADOS (
    id_pais         NUMBER(3) NOT NULL,
    id              NUMBER(5) NOT NULL,
    nombre          VARCHAR2(25) NOT NULL,
    CONSTRAINT PK_ESTADOS PRIMARY KEY (id_pais, id),
    CONSTRAINT FK_ESTADOS_PAIS FOREIGN KEY (id_pais) REFERENCES PAISES (id)
);

CREATE TABLE CIUDADES (
    id_pais         NUMBER(3) NOT NULL,
    id_estado       NUMBER(5) NOT NULL,
    id              NUMBER(5) NOT NULL,
    nombre          VARCHAR2(25) NOT NULL,
    CONSTRAINT PK_CIUDADES PRIMARY KEY (id_pais, id_estado, id),
    CONSTRAINT FK_CIUDADES_ESTADO FOREIGN KEY (id_pais, id_estado) 
    REFERENCES ESTADOS (id_pais, id)
);

-- 2. PERSONAS (CLIENTES Y VISITANTES)

CREATE TABLE CLIENTES (
    id_lego             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    primer_nombre       VARCHAR2(20) NOT NULL,
    primer_apellido     VARCHAR2(20) NOT NULL,
    segundo_apellido    VARCHAR2(20) NOT NULL,
    email               VARCHAR2(30) NOT NULL UNIQUE,
    doc_identidad       VARCHAR2(10) NOT NULL UNIQUE,
    pasaporte  VARCHAR2(10) NOT NULL,
    fecha_nacimiento    DATE NOT NULL,
    id_pais_res         NUMBER NOT NULL,
    id_pais_nac         NUMBER NOT NULL,
    segundo_nombre      VARCHAR2(20),
    fecha_venc_pasa     DATE,
    CONSTRAINT PK_CLIENTES PRIMARY KEY (id_lego),
    CONSTRAINT FK_CLIENTE_PAIS_RES FOREIGN KEY (id_pais_res) REFERENCES PAIS (id),
    CONSTRAINT FK_CLIENTE_PAIS_NAC FOREIGN KEY (id_pais_nac) REFERENCES PAIS (id)
);

CREATE TABLE VISITANTES (
    id_lego             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    primer_nombre       VARCHAR2(20) NOT NULL,
    primer_apellido     VARCHAR2(20) NOT NULL,
    segundo_apellido    VARCHAR2(20) NOT NULL,
    doc_identidad       VARCHAR2(20) NOT NULL,
    fecha_nacimiento    DATE NOT NULL,
    pasaporte  VARCHAR2(10) NOT NULL,
    id_pais_nac         NUMBER NOT NULL,
    id_cliente_repres   NUMBER, -- Puede ser nulo si es mayor de 18
    segundo_nombre      VARCHAR2(20),
    fecha_venc_pasa     DATE,
    CONSTRAINT PK_VISITANTES PRIMARY KEY (id_lego),
    CONSTRAINT UQ_VISITANTES_DOC UNIQUE (doc_identidad),
    CONSTRAINT FK_VISITANTE_PAIS FOREIGN KEY (id_pais_nac) REFERENCES PAIS (id),
    CONSTRAINT FK_VISITANTE_REPRES FOREIGN KEY (id_cliente_repres) REFERENCES CLIENTES (id_lego)
);

-- 3. PRODUCTOS Y CATÁLOGO
CREATE TABLE PRODUCTOS_JUGUETES_LEGO (
    id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre          VARCHAR2(40) NOT NULL,
    descripcion     VARCHAR2(250) NOT NULL,
    rango_edad      VARCHAR2(20) NOT NULL,
    rango_precio    VARCHAR2(20) NOT NULL,
    j_set           CHAR(2) CHECK (j_set IN ('SI', 'NO')),
    set_detalle     NUMBER,
    instrucciones   VARCHAR2(3000),
    nro_piezas      NUMBER,
    CONSTRAINT PK_PRODUCTOS PRIMARY KEY (id),
    CONSTRAINT UQ_PRODUCTOS_NOMBRE UNIQUE (nombre),
    CONSTRAINT FK_PROD_SET_DETALLE FOREIGN KEY (set_detalle) REFERENCES PRODUCTOS_JUGUETES_LEGO (id)
);

CREATE TABLE CATALOGO_PAIS (
    id_pais         NUMBER NOT NULL,
    id_producto_juguete_lego NUMBER NOT NULL,
    limite_compra   NUMBER NOT NULL,
  
    CONSTRAINT PK_CATALOGO_PAIS PRIMARY KEY (id_pais),
    CONSTRAINT FK_CATALOGO_PAIS FOREIGN KEY (id_pais) REFERENCES PAIS (id),
    CONSTRAINT FK_CATALOGO_PROD FOREIGN KEY (id_producto_juguete_lego) REFERENCES PRODUCTOS_JUGUETES_LEGO (id)
);

CREATE TABLE HIST_PRECIOS (
    id_producto     NUMBER NOT NULL,
    fecha_inicio    DATE NOT NULL,
    fecha_fin       DATE,
    precio          NUMBER(10, 2) NOT NULL,
    CONSTRAINT PK_HIST_PRECIOS PRIMARY KEY (id_producto, fecha_inicio),
    CONSTRAINT FK_HIST_PROD FOREIGN KEY (id_producto) REFERENCES PRODUCTOS_JUGUETES_LEGO (id)
);

CREATE TABLE PRODUCTOS_RELACION (
    id_producto_a   NUMBER NOT NULL,
    id_producto_b   NUMBER NOT NULL,
    CONSTRAINT PK_PROD_RELACION PRIMARY KEY (id_producto_a, id_producto_b),
    CONSTRAINT FK_REL_PROD_A FOREIGN KEY (id_producto_a) REFERENCES PRODUCTOS_JUGUETES_LEGO (id),
    CONSTRAINT FK_REL_PROD_B FOREIGN KEY (id_producto_b) REFERENCES PRODUCTOS_JUGUETES_LEGO (id)
);

-- 4. TEMAS Y TOURS
CREATE TABLE TEMAS (
    id                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre              VARCHAR2(20) NOT NULL,
    descripcion         VARCHAR2(250) NOT NULL,
    tipo                CHAR(2) CHECK (tipo IN ('T', 'S')) NOT NULL,
// (T = Tema) y( S = Serie)
    id_tema_principal   NUMBER,
    CONSTRAINT PK_TEMAS PRIMARY KEY (id),
    CONSTRAINT UQ_TEMAS_NOMBRE UNIQUE (nombre),
    CONSTRAINT FK_TEMAS_RECURSIVA FOREIGN KEY (id_tema_principal) REFERENCES TEMAS (id)
);

CREATE TABLE TEMAS_PRODUCTOS (
    id_tema     NUMBER NOT NULL,
    id_producto NUMBER NOT NULL,
    CONSTRAINT PK_TEMAS_PRODUCTOS PRIMARY KEY (id_tema, id_producto),
    CONSTRAINT FK_TP_TEMA FOREIGN KEY (id_tema) REFERENCES TEMAS (id),
    CONSTRAINT FK_TP_PROD FOREIGN KEY (id_producto) REFERENCES PRODUCTOS_JUGUETES_LEGO (id)
);

CREATE TABLE TOURS (
    fecha_inicio        DATE ,
    precio_por_persona  NUMBER(10, 2) NOT NULL,
    capacidad_maxima    NUMBER NOT NULL,
    regala_producto     CHAR(2) CHECK (regala_producto IN ('SI', 'NO')) NOT NULL,
    descripcion_producto VARCHAR2(250),
    CONSTRAINT PK_TOURS PRIMARY KEY (fecha_inicio)
);

-- 5. OPERACIONES
CREATE TABLE INSCRIPCION (
    numero          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_tour         NUMBER NOT NULL,
    fecha           DATE NOT NULL,
    costo_total     NUMBER(10, 2) NOT NULL,
    status          NUMBER DEFAULT 1 NOT NULL, 
    CONSTRAINT PK_INSCRIPCION PRIMARY KEY (numero,id_tour ),
    CONSTRAINT FK_INSCRIPCION_TOUR FOREIGN KEY (id_tour) REFERENCES TOURS (id)
);

CREATE TABLE INSCRITOS (
    id                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nro_inscripcion     NUMBER NOT NULL,
    id_visitante_lego   NUMBER NOT NULL,
    id_cliente_lego     NUMBER NOT NULL,
    CONSTRAINT PK_INSCRITOS PRIMARY KEY (id,nro_inscripcion  ),
    CONSTRAINT FK_INSCRITOS_INSCRIP FOREIGN KEY (nro_inscripcion) REFERENCES INSCRIPCION (numero),
    CONSTRAINT FK_INSCRITOS_VISIT FOREIGN KEY (id_visitante_lego) REFERENCES VISITANTES (id_lego),
    CONSTRAINT FK_INSCRITOS_CLIENTE FOREIGN KEY (id_cliente_lego) REFERENCES CLIENTES (id_lego)
);

CREATE TABLE ENTRADAS (
    nro_inscripcion NUMBER NOT NULL,
    id              NUMBER NOT NULL,
    tipo_cliente    CHAR(2) CHECK (tipo_cliente IN ('A', 'N')) NOT NULL,

--// ‘A’ significa ADULTO, ‘N’ significa NINO

    CONSTRAINT PK_ENTRADAS PRIMARY KEY (nro_inscripcion, id),
    CONSTRAINT FK_ENTRADAS_INSCRIP FOREIGN KEY (nro_inscripcion) REFERENCES INSCRIPCION (numero)
);

CREATE TABLE TIENDAS (
    id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre          VARCHAR2(25) NOT NULL,
    nro_telefono    VARCHAR2(20) NOT NULL,
    direccion       VARCHAR2(200) NOT NULL,
    id_pais         NUMBER NOT NULL,
    id_estado       NUMBER NOT NULL,
    id_ciudad       NUMBER NOT NULL,
    CONSTRAINT PK_TIENDAS PRIMARY KEY (id),
    CONSTRAINT UQ_TIENDAS_NOMBRE UNIQUE (nombre),
    CONSTRAINT FK_TIENDAS_CIUDAD FOREIGN KEY (id_pais, id_estado, id_ciudad) 
        REFERENCES CIUDADES (id_pais, id_estado, id)
);

CREATE TABLE HORARIOS (

    dia_semana      NUMBER NOT NULL,
    hora_apertura   VARCHAR2(10) NOT NULL,
    hora_cierre     VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_HORARIOS PRIMARY KEY ( dia_semana),
    CONSTRAINT FK_HORARIOS_TIENDA FOREIGN KEY (id_tienda) REFERENCES TIENDAS (id)
);

-- 6. FACTURACIÓN E INVENTARIO
CREATE TABLE FACTURAS_TIENDA (
    nro_factura     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_tienda       NUMBER NOT NULL,
    total           NUMBER(10, 2) NOT NULL,
    fecha_emision   DATE NOT NULL,
    id_cliente_lego NUMBER NOT NULL,
    CONSTRAINT PK_FACTURAS_TIENDA PRIMARY KEY (nro_factura,id_tienda),
    CONSTRAINT FK_FACT_TIENDA FOREIGN KEY (id_tienda) REFERENCES TIENDAS (id),
    CONSTRAINT FK_FACT_CLIENTE FOREIGN KEY (id_cliente_lego) REFERENCES CLIENTES (id_lego)
);


CREATE TABLE DETALLES_FACTURA (
    nro_factura     NUMBER NOT NULL,
    id              NUMBER NOT NULL,
    cantidad        NUMBER NOT NULL,
    tipo_cliente    CHAR(2) CHECK (tipo_cliente IN ('A', 'N')) NOT NULL,

--// ‘A’ significa ADULTO, ‘N’ significa NINO

    CONSTRAINT PK_DETALLES_FACTURA PRIMARY KEY (nro_factura, id),
    CONSTRAINT FK_DET_FACTURA FOREIGN KEY (nro_factura) REFERENCES FACTURAS_TIENDA (nro_factura)
);

CREATE TABLE LOTES_INVENTARIO (
    id_lote         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
     id_tienda       NUMBER NOT NULL,
    id_producto     NUMBER NOT NULL,
    cantidad        NUMBER NOT NULL,
    CONSTRAINT PK_LOTES PRIMARY KEY (id_lote,id_tienda,id_producto),
    CONSTRAINT FK_LOTES_TIENDA FOREIGN KEY (id_tienda) REFERENCES TIENDAS (id),
    CONSTRAINT FK_LOTES_PROD FOREIGN KEY (id_producto) REFERENCES PRODUCTOS_JUGUETES_LEGO (id)
);

CREATE TABLE DESCUENTO_L_INVENTARIO (
    id_lote         NUMBER NOT NULL,
    id_tienda       NUMBER NOT NULL,
    id_producto     NUMBER NOT NULL,
    id              NUMBER NOT NULL,
    fecha           DATE NOT NULL,
    cant_descontar  NUMBER NOT NULL,
    es_salida       BOOLEAN NOT NULL, 
    CONSTRAINT PK_DESC_INVENTARIO PRIMARY KEY (id_lote, id_tienda ,id_producto ,id),
    CONSTRAINT FK_DESC_LOTE FOREIGN KEY (id_lote) REFERENCES LOTES_INVENTARIO (id_lote),
    CONSTRAINT FK_DESC_LOTE FOREIGN KEY (id_producto ) REFERENCES LOTES_INVENTARIO (id_producto ),
    CONSTRAINT FK_DESC_LOTE FOREIGN KEY (id_tienda) REFERENCES LOTES_INVENTARIO (id_tienda )
);


























/* ==========================================


   DESCRIPCIÓN: COPIA DEL PRIMER COMMIT PORCIA  IMPORTANTE 


   ========================================== */

-- 1. TABLAS DE UBICACIÓN
CREATE TABLE PAIS (
    id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre          VARCHAR2(100) NOT NULL,
    continente      VARCHAR2(50) NOT NULL,
    nacionalidad    VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_PAIS PRIMARY KEY (id),
    CONSTRAINT UQ_PAIS_NOMBRE UNIQUE (nombre)
);

CREATE TABLE ESTADOS (
    id_pais         NUMBER NOT NULL,
    id              NUMBER NOT NULL,
    nombre          VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_ESTADOS PRIMARY KEY (id_pais, id),
    CONSTRAINT FK_ESTADOS_PAIS FOREIGN KEY (id_pais) REFERENCES PAIS (id)
);

CREATE TABLE CIUDADES (
    id_pais         NUMBER NOT NULL,
    id_estado       NUMBER NOT NULL,
    id              NUMBER NOT NULL,
    nombre          VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_CIUDADES PRIMARY KEY (id_pais, id_estado, id),
    CONSTRAINT FK_CIUDADES_ESTADO FOREIGN KEY (id_pais, id_estado) 
        REFERENCES ESTADOS (id_pais, id)
);

-- 2. PERSONAS (CLIENTES Y VISITANTES)

CREATE TABLE CLIENTES (
    id_lego             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    primer_nombre       VARCHAR2(100) NOT NULL,
    segundo_nombre      VARCHAR2(100),
    primer_apellido     VARCHAR2(100) NOT NULL,
    segundo_apellido    VARCHAR2(100),
    email               VARCHAR2(150) NOT NULL,
    doc_identidad       VARCHAR2(50) NOT NULL,
    fecha_venc_pasa     DATE,
    fecha_nacimiento    DATE NOT NULL,
    id_pais_res         NUMBER NOT NULL,
    id_pais_nac         NUMBER NOT NULL,
    CONSTRAINT PK_CLIENTES PRIMARY KEY (id_lego),
    CONSTRAINT UQ_CLIENTES_EMAIL UNIQUE (email),
    CONSTRAINT UQ_CLIENTES_DOC UNIQUE (doc_identidad),
    CONSTRAINT FK_CLIENTE_PAIS_RES FOREIGN KEY (id_pais_res) REFERENCES PAIS (id),
    CONSTRAINT FK_CLIENTE_PAIS_NAC FOREIGN KEY (id_pais_nac) REFERENCES PAIS (id)
);

CREATE TABLE VISITANTES (
    id_lego             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    primer_nombre       VARCHAR2(100) NOT NULL,
    segundo_nombre      VARCHAR2(100),
    primer_apellido     VARCHAR2(100) NOT NULL,
    segundo_apellido    VARCHAR2(100),
    doc_identidad       VARCHAR2(50) NOT NULL,
    fecha_venc_pasa     DATE,
    fecha_nacimiento    DATE NOT NULL,
    id_pais_nac         NUMBER NOT NULL,
    id_cliente_repres   NUMBER, -- Puede ser nulo si es mayor de 18
    CONSTRAINT PK_VISITANTES PRIMARY KEY (id_lego),
    CONSTRAINT UQ_VISITANTES_DOC UNIQUE (doc_identidad),
    CONSTRAINT FK_VISITANTE_PAIS FOREIGN KEY (id_pais_nac) REFERENCES PAIS (id),
    CONSTRAINT FK_VISITANTE_REPRES FOREIGN KEY (id_cliente_repres) REFERENCES CLIENTES (id_lego)
);

-- 3. PRODUCTOS Y CATÁLOGO
CREATE TABLE PRODUCTOS_JUGUETES_LEGO (
    id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre          VARCHAR2(150) NOT NULL,
    nro_piezas      NUMBER,
    descripcion     VARCHAR2(4000),
    instrucciones   VARCHAR2(255),
    rango_edad      VARCHAR2(50),
    rango_precio    VARCHAR2(50),
    j_set           CHAR(2) CHECK (j_set IN ('SI', 'NO')),
    set_detalle     NUMBER,
    CONSTRAINT PK_PRODUCTOS PRIMARY KEY (id),
    CONSTRAINT UQ_PRODUCTOS_NOMBRE UNIQUE (nombre),
    CONSTRAINT FK_PROD_SET_DETALLE FOREIGN KEY (set_detalle) REFERENCES PRODUCTOS_JUGUETES_LEGO (id)
);

CREATE TABLE CATALOGO_PAIS (
    id_pais         NUMBER NOT NULL,
    limite_compra   NUMBER NOT NULL,
    id_producto_juguete_lego NUMBER NOT NULL,
    CONSTRAINT PK_CATALOGO_PAIS PRIMARY KEY (id_pais),
    CONSTRAINT FK_CATALOGO_PAIS FOREIGN KEY (id_pais) REFERENCES PAIS (id),
    CONSTRAINT FK_CATALOGO_PROD FOREIGN KEY (id_producto_juguete_lego) REFERENCES PRODUCTOS_JUGUETES_LEGO (id)
);

CREATE TABLE HIST_PRECIOS (
    id_producto     NUMBER NOT NULL,
    fecha_inicio    DATE NOT NULL,
    fecha_fin       DATE,
    precio          NUMBER(10, 2) NOT NULL,
    CONSTRAINT PK_HIST_PRECIOS PRIMARY KEY (id_producto, fecha_inicio),
    CONSTRAINT FK_HIST_PROD FOREIGN KEY (id_producto) REFERENCES PRODUCTOS_JUGUETES_LEGO (id)
);

CREATE TABLE PRODUCTOS_RELACION (
    id_producto_a   NUMBER NOT NULL,
    id_producto_b   NUMBER NOT NULL,
    CONSTRAINT PK_PROD_RELACION PRIMARY KEY (id_producto_a, id_producto_b),
    CONSTRAINT FK_REL_PROD_A FOREIGN KEY (id_producto_a) REFERENCES PRODUCTOS_JUGUETES_LEGO (id),
    CONSTRAINT FK_REL_PROD_B FOREIGN KEY (id_producto_b) REFERENCES PRODUCTOS_JUGUETES_LEGO (id)
);

-- 4. TEMAS Y TOURS
CREATE TABLE TEMAS (
    id                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre              VARCHAR2(100) NOT NULL,
    descripcion         VARCHAR2(4000) NOT NULL,
    tipo                VARCHAR2(20) CHECK (tipo IN ('TEMA', 'SERIE')) NOT NULL,
    id_tema_principal   NUMBER,
    CONSTRAINT PK_TEMAS PRIMARY KEY (id),
    CONSTRAINT UQ_TEMAS_NOMBRE UNIQUE (nombre),
    CONSTRAINT FK_TEMAS_RECURSIVA FOREIGN KEY (id_tema_principal) REFERENCES TEMAS (id)
);

CREATE TABLE TEMAS_PRODUCTOS (
    id_tema     NUMBER NOT NULL,
    id_producto NUMBER NOT NULL,
    CONSTRAINT PK_TEMAS_PRODUCTOS PRIMARY KEY (id_tema, id_producto),
    CONSTRAINT FK_TP_TEMA FOREIGN KEY (id_tema) REFERENCES TEMAS (id),
    CONSTRAINT FK_TP_PROD FOREIGN KEY (id_producto) REFERENCES PRODUCTOS_JUGUETES_LEGO (id)
);

CREATE TABLE TOURS (
    id                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    fecha_inicio        DATE NOT NULL,
    precio_por_persona  NUMBER(10, 2) NOT NULL,
    capacidad_maxima    NUMBER NOT NULL,
    regala_producto     CHAR(2) CHECK (regala_producto IN ('SI', 'NO')) NOT NULL,
    descripcion_producto VARCHAR2(4000),
    CONSTRAINT PK_TOURS PRIMARY KEY (id)
);

-- 5. OPERACIONES
CREATE TABLE INSCRIPCION (
    numero          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    fecha           DATE NOT NULL,
    costo_total     NUMBER(10, 2) NOT NULL,
    status          NUMBER DEFAULT 1 NOT NULL, 
    id_tour         NUMBER,
    CONSTRAINT PK_INSCRIPCION PRIMARY KEY (numero),
    CONSTRAINT FK_INSCRIPCION_TOUR FOREIGN KEY (id_tour) REFERENCES TOURS (id)
);

CREATE TABLE INSCRITOS (
    id                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nro_inscripcion     NUMBER NOT NULL,
    id_visitante_lego   NUMBER NOT NULL,
    id_cliente_lego     NUMBER NOT NULL,
    CONSTRAINT PK_INSCRITOS PRIMARY KEY (id),
    CONSTRAINT FK_INSCRITOS_INSCRIP FOREIGN KEY (nro_inscripcion) REFERENCES INSCRIPCION (numero),
    CONSTRAINT FK_INSCRITOS_VISIT FOREIGN KEY (id_visitante_lego) REFERENCES VISITANTES (id_lego),
    CONSTRAINT FK_INSCRITOS_CLIENTE FOREIGN KEY (id_cliente_lego) REFERENCES CLIENTES (id_lego)
);

CREATE TABLE ENTRADAS (
    nro_inscripcion NUMBER NOT NULL,
    id              NUMBER NOT NULL,
    tipo_cliente    VARCHAR2(20) CHECK (tipo_cliente IN ('ADULTO', 'NINO')) NOT NULL,
    CONSTRAINT PK_ENTRADAS PRIMARY KEY (nro_inscripcion, id),
    CONSTRAINT FK_ENTRADAS_INSCRIP FOREIGN KEY (nro_inscripcion) REFERENCES INSCRIPCION (numero)
);

CREATE TABLE TIENDAS (
    id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre          VARCHAR2(100) NOT NULL,
    nro_telefono    VARCHAR2(20) NOT NULL,
    direccion       VARCHAR2(200) NOT NULL,
    id_pais         NUMBER NOT NULL,
    id_estado       NUMBER NOT NULL,
    id_ciudad       NUMBER NOT NULL,
    CONSTRAINT PK_TIENDAS PRIMARY KEY (id),
    CONSTRAINT UQ_TIENDAS_NOMBRE UNIQUE (nombre),
    CONSTRAINT FK_TIENDAS_CIUDAD FOREIGN KEY (id_pais, id_estado, id_ciudad) 
        REFERENCES CIUDADES (id_pais, id_estado, id)
);

CREATE TABLE HORARIOS (
    id_tienda       NUMBER NOT NULL,
    dia_semana      VARCHAR2(20) NOT NULL,
    hora_apertura   VARCHAR2(10) NOT NULL,
    hora_cierre     VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_HORARIOS PRIMARY KEY (id_tienda, dia_semana),
    CONSTRAINT FK_HORARIOS_TIENDA FOREIGN KEY (id_tienda) REFERENCES TIENDAS (id)
);

-- 6. FACTURACIÓN E INVENTARIO
CREATE TABLE FACTURAS_TIENDA (
    nro_factura     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    total           NUMBER(10, 2) NOT NULL,
    fecha_emision   DATE NOT NULL,
    id_tienda       NUMBER NOT NULL,
    id_cliente_lego NUMBER NOT NULL,
    CONSTRAINT PK_FACTURAS_TIENDA PRIMARY KEY (nro_factura),
    CONSTRAINT FK_FACT_TIENDA FOREIGN KEY (id_tienda) REFERENCES TIENDAS (id),
    CONSTRAINT FK_FACT_CLIENTE FOREIGN KEY (id_cliente_lego) REFERENCES CLIENTES (id_lego)
);

CREATE TABLE DETALLES_FACTURA (
    nro_factura     NUMBER NOT NULL,
    id              NUMBER NOT NULL,
    cantidad        NUMBER NOT NULL,
    tipo_cliente    VARCHAR2(20) CHECK (tipo_cliente IN ('ADULTO', 'NINO')) NOT NULL,
    CONSTRAINT PK_DETALLES_FACTURA PRIMARY KEY (nro_factura, id),
    CONSTRAINT FK_DET_FACTURA FOREIGN KEY (nro_factura) REFERENCES FACTURAS_TIENDA (nro_factura)
);

CREATE TABLE LOTES_INVENTARIO (
    id_lote         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    cantidad        NUMBER NOT NULL,
    id_tienda       NUMBER NOT NULL,
    id_producto     NUMBER NOT NULL,
    CONSTRAINT PK_LOTES PRIMARY KEY (id_lote),
    CONSTRAINT FK_LOTES_TIENDA FOREIGN KEY (id_tienda) REFERENCES TIENDAS (id),
    CONSTRAINT FK_LOTES_PROD FOREIGN KEY (id_producto) REFERENCES PRODUCTOS_JUGUETES_LEGO (id)
);

CREATE TABLE DESCUENTO_L_INVENTARIO (
    id_lote         NUMBER NOT NULL,
    id              NUMBER NOT NULL,
    fecha           DATE NOT NULL,
    cant_descontar  NUMBER NOT NULL,
    es_salida       BOOLEAN NOT NULL, 
    CONSTRAINT PK_DESC_INVENTARIO PRIMARY KEY (id_lote, id),
    CONSTRAINT FK_DESC_LOTE FOREIGN KEY (id_lote) REFERENCES LOTES_INVENTARIO (id_lote)
);
