
-- 1. FACTURACIÓN ONLINE
DROP TABLE DET_FACTURAS_ONLINE CASCADE CONSTRAINTS;
DROP TABLE FACTURAS_ONLINE CASCADE CONSTRAINTS;

-- 2. INVENTARIO Y FACTURACIÓN TIENDA
DROP TABLE DESCUENTO_L_INVENTARIO CASCADE CONSTRAINTS;
DROP TABLE LOTES_INVENTARIO CASCADE CONSTRAINTS;
DROP TABLE DETALLES_FACTURA_TIENDA CASCADE CONSTRAINTS;
DROP TABLE FACTURAS_TIENDA CASCADE CONSTRAINTS;

-- 3. TIENDAS Y HORARIOS
DROP TABLE HORARIOS CASCADE CONSTRAINTS;
DROP TABLE TIENDAS CASCADE CONSTRAINTS;

-- 4. TOURS, INSCRIPCIONES Y ENTRADAS
DROP TABLE ENTRADAS CASCADE CONSTRAINTS;
DROP TABLE INSCRITOS CASCADE CONSTRAINTS;
DROP TABLE INSCRIPCIONES CASCADE CONSTRAINTS;
DROP TABLE TOURS CASCADE CONSTRAINTS;

-- 5. TEMAS Y PRODUCTOS
DROP TABLE TEMAS_JUGUETES CASCADE CONSTRAINTS;
DROP TABLE TEMAS CASCADE CONSTRAINTS;
DROP TABLE PRODUCTOS_RELACION CASCADE CONSTRAINTS;
DROP TABLE HIST_PRECIOS CASCADE CONSTRAINTS;
DROP TABLE CATALOGO_PAISES CASCADE CONSTRAINTS;
DROP TABLE JUGUETES_LEGO CASCADE CONSTRAINTS;

-- 6. PERSONAS
DROP TABLE VISITANTE_MENORES CASCADE CONSTRAINTS;
DROP TABLE CLIENTES CASCADE CONSTRAINTS;

-- 7. UBICACIÓN (Borrar al final porque casi todo depende de esto)
DROP TABLE CIUDADES CASCADE CONSTRAINTS;
DROP TABLE ESTADOS CASCADE CONSTRAINTS;
DROP TABLE PAISES CASCADE CONSTRAINTS;
-----------------------------------------------------------------------------------------------------

-- 1. Borrar trigger de validación de edad (21 años)
DROP TRIGGER trg_bi_fact_tienda_cliente;
-- 2. Borrar trigger de límite de compra por país/producto
DROP TRIGGER trg_bi_det_tienda_limite;
-- 3. Borrar trigger de histórico de precios (Compound Trigger)
DROP TRIGGER trg_bi_hist_precio_fechas;


COMMIT;
